//
//  BLEController for BackgroundBLE project
//
//  Owns and handles BLE communications and events.
//
//  Created by D S on 8/16/20.
//

import Foundation
import CoreBluetooth

// structure to pas additional information about Peripheral into View
struct PeripheralDescr: Hashable {
    // using identifier as it should be unique
    static func == (lhs: PeripheralDescr, rhs: PeripheralDescr) -> Bool {
        return lhs.peripheral.identifier == rhs.peripheral.identifier
    }
    
    var name : String
    let services : [CBUUID]
    let identifier : UUID
    var peripheral : CBPeripheral
}

class BLEModel : NSObject, CBCentralManagerDelegate, CBPeripheralManagerDelegate, ObservableObject {
    
    var centralManager: CBCentralManager!
    var peripheralManager: CBPeripheralManager!
    // array of peripheral scanned in central mode
    @Published var peripherals: [PeripheralDescr] = []
    
    // UUIDs of service and characteristic -- hardcoded
    // Can be generated by running `uuidgen` in the Mac's terminal
    // source: https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/CoreBluetooth_concepts/PerformingCommonPeripheralRoleTasks/PerformingCommonPeripheralRoleTasks.html#//apple_ref/doc/uid/TP40013257-CH4-SW1
    
    var myServiceUUID: CBUUID
    var myCharacteristicUUID: CBUUID
    
    var myService: CBMutableService
    var myCharacteristic: CBMutableCharacteristic
    var centralManagerIsOn: Bool {
        get {
            return self.centralManager?.isScanning == true
        }
        set (toggleCentral){
            if toggleCentral == true {
                self.startScan()
            } else {
                self.cancelScan()
                peripherals = []
            }
        }
    }
    var peripheralManagerIsOn: Bool {
        get {
            return self.peripheralManager?.isAdvertising == true
        }
        set (togglePress){
            if togglePress == true {
                self.startAdvertising()
            } else {
                self.stopAdvertising()
            }
        }
    }
    override init() {
        
        self.myServiceUUID = CBUUID(string: "71DA3FD1-7E10-41C1-B16F-4430B506CDE7")
        self.myCharacteristicUUID = CBUUID(string: "523D0E52-01CE-4AA7-A525-E99AC9FE2AC6")
        
        self.myCharacteristic = CBMutableCharacteristic(type: self.myCharacteristicUUID, properties: [.notify, .read], value: nil, permissions: [.readable])
        
        self.myService = CBMutableService(type: self.myServiceUUID, primary: true)
        self.myService.characteristics = [self.myCharacteristic]
        
        super.init()

        // configure central mode
        self.peripheralManager = CBPeripheralManager(delegate: self, queue: nil)
        // configure peripheral mode
        self.centralManager = CBCentralManager(delegate: self, queue: nil)
        print("initiated all variables")
    }
    
    func startScan() {
        peripherals = []
        if self.peripheralManager?.isAdvertising == true {
            self.stopAdvertising()
        }
        // start scanning for all devices
        // to scan in the background, need to specify serviceUUID
        centralManager?.scanForPeripherals(withServices: [self.myServiceUUID], options: [CBCentralManagerScanOptionAllowDuplicatesKey:false])
        print("started the scan")
    }
    
    func cancelScan() {
        self.centralManager?.stopScan()
        print("Scan Stopped")
        print("Number of Peripherals Found: \(peripherals.count)")
    }
    
    func centralManagerDidUpdateState(_ central: CBCentralManager) {
        switch central.state {
            case CBManagerState.poweredOn:
                print("central is powered on")
            case CBManagerState.unauthorized:
                print("Unauthorized for BLE")
            case CBManagerState.poweredOff:
                print("Powered Off from central manager")
            default:
                print("other error encountered")
        }
    }
    func centralManager(_ central: CBCentralManager, didDiscover peripheral: CBPeripheral,advertisementData: [String : Any], rssi RSSI: NSNumber) {
        print ("Detected")
        // get either the peripheral name or the name it is advertising
        let name : String = utilGetName(peripheral, advertisementData)
        let uuids : [CBUUID] = utilUUIDsOrDefault(advertisementData)
        peripherals.append(PeripheralDescr(name: name, services: uuids, identifier: peripheral.identifier, peripheral: peripheral ))
        
        print("Found new pheripheral devices with services")
        print("Peripheral name: \(String(describing: peripheral.identifier))")
        print("RSSI   : \(RSSI)")
        print("**********************************")
        print ("Advertisement Data : \(advertisementData)")
    }
    func startAdvertising() {
        // TODO see if first need to stop cental mode
        if self.centralManager?.isScanning == true {
            self.cancelScan();
        }
        if self.peripheralManager?.isAdvertising == true {
            return;
        } else {
            self.peripheralManager?.startAdvertising([CBAdvertisementDataLocalNameKey: "BLEFromIOS",
                                                      CBAdvertisementDataServiceUUIDsKey: [self.myServiceUUID]])
            print("start advertising")
        }
    }
    
    func stopAdvertising() {
        self.peripheralManager?.stopAdvertising()
        print("peripheral stopped advertising")
    }
    
    func peripheralManagerDidStartAdvertising(_ peripheral: CBPeripheralManager, error: Error?) {
        if error != nil {
            print(error as Any)
        } else {
            print ("started advertising")
        }
    }
    func peripheralManagerDidUpdateState(_ peripheral: CBPeripheralManager) {
        if (peripheral.state == CBManagerState.poweredOn) {
            print("Peripheral on")
            // in case the service has already been added
            self.peripheralManager?.removeAllServices()
            self.peripheralManager?.add(self.myService)
        } else {
            print("peripheral is connected")
        }
    }
    
    
}
